In [58]:
import tensorflow as tf

In [59]:
daily_sales_numbers=[21,22,-108,-1,32,34,31,73]

In [60]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [61]:
for sales in tf_dataset:
    print(sales.numpy())

21
22
-108
-1
32
34
31
73


In [62]:
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


In [63]:
tf_dataset=tf_dataset.filter(lambda x:x>0)
for sales in tf_dataset:
    print(sales.numpy())

21
22
32
34
31
73


In [64]:
tf_dataset=tf_dataset.map(lambda x:x*84)
for sales in tf_dataset:
    print(sales.numpy())

1764
1848
2688
2856
2604
6132


In [65]:
tf_dataset=tf_dataset.shuffle(3)
for sales in tf_dataset:
    print(sales.numpy())

1848
2856
2688
6132
1764
2604


In [66]:
for sales_batch in tf_dataset.batch(4):
    print(sales_batch.numpy())

[1764 2688 2604 6132]
[1848 2856]


In [67]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset=tf_dataset.filter(lambda x:x>0).map(lambda y:y*84).shuffle(2).batch(2)
for sales in tf_dataset:
    print(sales.numpy())


[1764 2688]
[1848 2604]
[6132 2856]


In [68]:
images_ds=tf.data.Dataset.list_files('images/*/*',shuffle=False)
for img in images_ds.take(4):
    print(img.numpy())

b'images\\cats\\11a15460b08386169286d76559da0b13.jpg'
b'images\\cats\\1200px-Cat03.jpg'
b'images\\cats\\1200px-Cat_November_2010-1a.jpg'
b'images\\cats\\1310870.jpg'


In [69]:
images_ds=images_ds.shuffle(200)
for img in images_ds.take(4):
    print(img.numpy())

b"images\\cats\\sweet-view-animal-fur-green-kitten-cat-mammal-fauna-eyes-whiskers-grey-vertebrate-out-domestic-cat-bobcat-cat's-eyes-tabby-cat-green-eyes-european-shorthair-grey-fur-wild-cat-small-to-medium-.jpg"
b'images\\dogs\\small-dog-owners-1.jpg'
b'images\\cats\\GettyImages-1341465008.jpg'
b'images\\cats\\Savannah_Cat_portrait.jpg'


In [70]:
class_names=["cat","dog"]


In [71]:
image_count=len(images_ds)
image_count

60

In [72]:
train_size=int(image_count*0.8)
train_ds=images_ds.take(train_size)
test_ds=images_ds.skip(train_size)

In [73]:
len(train_ds)


48

In [74]:
len(test_ds)

12

In [75]:
s='images\\dogs\\cutest-dog-breeds-jpg.jpg'
s=s.split("\\")
s

['images', 'dogs', 'cutest-dog-breeds-jpg.jpg']

In [76]:
s[-2]

'dogs'

In [77]:
def get_label(file_path):
    import os
    return tf.strings.split(file_path,os.path.sep)[-2]


In [78]:
for lable in train_ds.map(get_label):
    print(lable.numpy())

b'cats'
b'cats'
b'cats'
b'cats'
b'cats'
b'cats'
b'dogs'
b'dogs'
b'cats'
b'cats'
b'dogs'
b'dogs'
b'cats'
b'cats'
b'dogs'
b'dogs'
b'dogs'
b'cats'
b'cats'
b'dogs'
b'cats'
b'cats'
b'dogs'
b'dogs'
b'cats'
b'dogs'
b'dogs'
b'cats'
b'cats'
b'dogs'
b'dogs'
b'dogs'
b'dogs'
b'cats'
b'dogs'
b'dogs'
b'dogs'
b'cats'
b'dogs'
b'cats'
b'cats'
b'dogs'
b'dogs'
b'dogs'
b'cats'
b'dogs'
b'cats'
b'cats'


In [85]:
def process_img(file_path):
    label=get_label(file_path)
    img=tf.io.read_file(file_path)
    img=tf.image.decode_jpeg(img)
    img=tf.image.resize(img,[128,128])
    return img,label


In [89]:
for img, lable in train_ds.map(process_img).take(3):
    print(lable)
    print(img)

tf.Tensor(b'cats', shape=(), dtype=string)
tf.Tensor(
[[[3.06250000e+00 0.00000000e+00 0.00000000e+00]
  [3.12500000e+00 0.00000000e+00 0.00000000e+00]
  [3.14062500e+00 3.90625000e-02 0.00000000e+00]
  ...
  [1.74289062e+02 1.82289062e+02 2.01289062e+02]
  [1.77773438e+02 1.85773438e+02 2.04773438e+02]
  [1.77867188e+02 1.88867188e+02 2.06867188e+02]]

 [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
  [1.00000000e+00 0.00000000e+00 0.00000000e+00]
  [1.00000000e+00 0.00000000e+00 0.00000000e+00]
  ...
  [1.82625000e+02 1.93625000e+02 2.11625000e+02]
  [1.80000000e+02 1.91000000e+02 2.09000000e+02]
  [1.83000000e+02 1.94000000e+02 2.12000000e+02]]

 [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
  [1.00000000e+00 0.00000000e+00 0.00000000e+00]
  [1.00000000e+00 0.00000000e+00 0.00000000e+00]
  ...
  [1.80257812e+02 1.91257812e+02 2.09257812e+02]
  [1.83375000e+02 1.95625000e+02 2.13000000e+02]
  [1.85750000e+02 1.94125000e+02 2.13000000e+02]]

 ...

 [[2.23710938e+02 2.26710938e+02 2

In [91]:
train_ds=train_ds.map(process_img)

In [90]:
def scale(img,lable):
    return img/255,lable

In [92]:
train_ds=train_ds.map(scale)

In [96]:
for img,lable in train_ds.take(3):
    
    print('img',img.numpy()[0][0])
    print("lable",lable.numpy())

img [0.18333334 0.19019608 0.11078431]
lable b'cats'
img [0.36078432 0.46666667 0.53333336]
lable b'cats'
img [0.79059434 0.7176471  0.5835478 ]
lable b'cats'
